#pragma once

#define CELL_UNUSED 0
#define CELL_SNAKE_BODY 1
#define CELL_SNAKE_HEAD 2
#define CELL_FOOD 3
#define DIRECTION_NORTH 4
#define DIRECTION_EAST 5
#define DIRECTION_SOUTH 6
#define DIRECTION_WEST 7
#define DIRECTION_NONE 8